apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-init
  namespace: kuber-03-apps
spec:
  selector:
    matchLabels:
      app: init
  replicas: 1
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
      - containerPort: 80
      initContainers:
      - name: busybox
        image: busybox:1.34
        command: ['sh', '-c', "until nslookup net-init-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginx-init-svc; sleep 2; done"]
