apiVersion: v1
kind: Pod
metadata:
   name: multitool
   namespace: kuber-03-apps
spec:
   containers:
     - name: multitool
       image: wbitt/network-multitool
       ports:
       - containerPort: 8080