apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
spec:
  selector:
    matchLabels:
      app: nmt
  replicas: 1
  template:
    metadata:
      labels:
        app: nmt
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        env:
          - name: HTTP_PORT
            value: "443"
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 1180
        env:
          - name: HTTP_PORT
            value: "11443"