apiVersion: v1
kind: Service
metadata:
  name: kuber-03-svc
  namespace: kuber-03-apps
spec:
  selector:
    app: nmt
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 1180
      targetPort: 1180



